# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5fdd16820fd4258b781ecc210e484bf2be66a5300811e1f1b9d40ea0a3bdba1bedf0c921004aeb577ac1c40f36b60b648cbb6512c421288aefb11c5ec620c45a

test:
  secret_key_base: eb243d3e9380b80e2f819abdeea30a0286d9136a03aa0f2dc655ffafcedb25e06f21a1463f201b701e8bbc92c21ee8ad45c357ffcc1e82602c0f35747ef7245f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
